#!/usr/bin/env bash
# build-project-image.sh — compose a per-workspace ccr image (ADR-0006).
#
# Reads .ccr/config.yaml (and/or .ccr/Dockerfile) at the given workspace and
# produces a final image tagged `<container-name>:latest-ccr`.
#
# Sources:
#   * image: <ref>     -> overlay ccr layer onto the upstream image
#   * build: <...>     -> first build user's Dockerfile, then overlay
#   * .ccr/Dockerfile  -> shorthand for `build:` with default paths
#   * none of the above -> exit 0, signalling the caller to fall back
#                         to the global `claude-container` image
#
# Output (stdout):
#   Final image tag, one line. Empty if no project image was built.
#
# Build-time validation of the chosen user (ADR-0006):
#   - uid != 0
#   - no sudoers entry anywhere
#   - exists in the base image (when `user:` is set explicitly)
#
# Assumes the base image is Debian/Ubuntu-derived (apt-get available).
# Non-Debian bases will fail the fuse3 install step.

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: build-project-image.sh <workspace-dir> <container-name>" >&2
    exit 2
fi

WORKSPACE=$1
CONT_NAME=$2

REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)
CCR_FUSE="$REPO_DIR/ccr-fuse/ccr-fuse-darwin-arm64"
if [ ! -x "$CCR_FUSE" ]; then
    echo "build-project-image: host ccr-fuse binary missing; run 'ccr build-host' first" >&2
    exit 1
fi

CONFIG="$WORKSPACE/.ccr/config.yaml"
DEFAULT_DOCKERFILE="$WORKSPACE/.ccr/Dockerfile"

# Resolve which source kind applies.
SOURCE=$("$CCR_FUSE" config --file "$CONFIG" field source 2>/dev/null || echo "default")
if [ "$SOURCE" = "default" ] && [ -f "$DEFAULT_DOCKERFILE" ]; then
    SOURCE="dockerfile_default"
fi
if [ "$SOURCE" = "default" ]; then
    # No project image needed; caller falls back to global claude-container.
    exit 0
fi

CCR_USER_CFG=$("$CCR_FUSE" config --file "$CONFIG" field user 2>/dev/null || echo "")
CCR_USER=${CCR_USER_CFG:-coder}
TAG="$CONT_NAME:latest-ccr"

# Step 1: produce the SOURCE_REF — the image used as the FROM line in the overlay.
case "$SOURCE" in
    image)
        SOURCE_REF=$("$CCR_FUSE" config --file "$CONFIG" field image)
        echo "build-project-image: source=image ref=$SOURCE_REF user=$CCR_USER" >&2
        ;;
    build)
        CTX_REL=$("$CCR_FUSE" config --file "$CONFIG" field context)
        DF_REL=$("$CCR_FUSE" config --file "$CONFIG" field dockerfile)
        CONTEXT=$(cd "$WORKSPACE/.ccr/$CTX_REL" && pwd)
        DOCKERFILE="$CONTEXT/$DF_REL"
        SOURCE_REF="$CONT_NAME:user"
        echo "build-project-image: source=build dockerfile=$DOCKERFILE context=$CONTEXT user=$CCR_USER" >&2
        container build -t "$SOURCE_REF" -f "$DOCKERFILE" "$CONTEXT" >&2
        ;;
    dockerfile_default)
        SOURCE_REF="$CONT_NAME:user"
        echo "build-project-image: source=.ccr/Dockerfile user=$CCR_USER" >&2
        container build -t "$SOURCE_REF" -f "$DEFAULT_DOCKERFILE" "$WORKSPACE/.ccr" >&2
        ;;
    *)
        echo "build-project-image: unknown source kind: $SOURCE" >&2
        exit 1
        ;;
esac

# Step 1.5: refuse non-Debian/Ubuntu bases up front. The overlay installs
# fuse3 via apt; Alpine, RHEL, Arch, distroless etc. are not supported in v1.
# Probing with an ephemeral container costs a few seconds but yields a clearer
# error than `apt-get: not found` deep inside the overlay build.
if ! container run --rm "$SOURCE_REF" sh -c '[ -f /etc/debian_version ]' >/dev/null 2>&1; then
    cat >&2 <<MSG
build-project-image: base image '$SOURCE_REF' is not Debian/Ubuntu-derived.

ccr's v1 overlay installs fuse3 via apt-get. Alpine, RHEL, Arch, distroless,
etc. bases are not supported yet. Use a Debian-based image
(debian:bookworm-slim, ubuntu:24.04, node:*-bookworm, python:*-slim-bookworm).

See docs/adr/0006-per-project-images-with-ccr-overlay.md for the restriction
and the path to widening it.
MSG
    exit 1
fi

# Step 2: generate overlay Dockerfile and build it.
OVERLAY_CTX=$(mktemp -d)
OVERLAY_DOCKERFILE="$OVERLAY_CTX/Dockerfile"
trap "rm -rf $OVERLAY_CTX" EXIT

USER_EXIST_CHECK=""
if [ -n "$CCR_USER_CFG" ]; then
    # User explicitly named in config: must exist in the base image (do not create).
    USER_EXIST_CHECK="RUN id -u $CCR_USER >/dev/null 2>&1 \\
    || (echo \"ccr-overlay: user '$CCR_USER' does not exist in base image\" >&2; exit 1)"
else
    # Default coder: create if missing.
    USER_EXIST_CHECK="RUN id -u $CCR_USER >/dev/null 2>&1 \\
    || useradd -m -s /bin/bash -u 1000 $CCR_USER"
fi

cat > "$OVERLAY_DOCKERFILE" <<EOF
# Auto-generated by ccr build-project-image.sh. Do not edit by hand.
FROM $SOURCE_REF
USER root
ENV DEBIAN_FRONTEND=noninteractive

# fuse3 — required for ccr-fuse to mount /workspace.
RUN apt-get update && apt-get install -y --no-install-recommends fuse3 \\
    && rm -rf /var/lib/apt/lists/*

# Allow non-root processes to access the FUSE mount.
RUN sed -i 's/^#user_allow_other/user_allow_other/' /etc/fuse.conf 2>/dev/null \\
    || echo 'user_allow_other' >> /etc/fuse.conf

# Container user (default coder, or whatever .ccr/config.yaml asked for).
$USER_EXIST_CHECK

# Hardening invariants per ADR-0006.
RUN test "\$(id -u $CCR_USER)" -ne 0 \\
    || (echo "ccr-overlay: user '$CCR_USER' is root, refusing" >&2; exit 1)
RUN ! grep -rqE "(^|[[:space:]])${CCR_USER}([[:space:]]|\$)" /etc/sudoers /etc/sudoers.d/ 2>/dev/null \\
    || (echo "ccr-overlay: user '$CCR_USER' has a sudoers entry, refusing" >&2; exit 1)

# Mount points for the shadow boundary.
RUN mkdir -p /var/lib/ccr/shadow /var/lib/ccr/backing /workspace /workspace-real \\
    && chmod 0700 /var/lib/ccr \\
    && chown root:root /var/lib/ccr /var/lib/ccr/shadow /var/lib/ccr/backing

# Pull ccr-fuse + init script from the locally-tagged ccr-base image.
COPY --from=ccr-base /usr/local/bin/ccr-fuse /usr/local/bin/ccr-fuse
COPY --from=ccr-base /usr/local/bin/ccr-init.sh /usr/local/bin/ccr-init.sh
RUN chmod 0755 /usr/local/bin/ccr-fuse /usr/local/bin/ccr-init.sh

WORKDIR /workspace
USER $CCR_USER
EOF

echo "build-project-image: building overlay -> $TAG" >&2
container build -t "$TAG" -f "$OVERLAY_DOCKERFILE" "$OVERLAY_CTX" >&2

# Emit the final tag for the Justfile recipe to capture.
echo "$TAG"
